.gitignore
go.mod
go.sum

go mod fix

---

int/api/html/front/website.html
int/api/html/front/website.js
int/api/websites/webcreator.go

Increase the upload limit to 4Mo

196-remove-website-size-upload-limit 

---

int/api/events.go
int/api/html/front/website.js

After a discussion with @SlnPons and @Trottoir , it was decided to implement a small optimization in the API event listener.

169 regression event manager not showing the chunk upload correctly

---

int/api/html/front/website.html
int/api/html/front/website.js
int/api/thyra.go
int/api/utils.go
int/api/websites/webcreator.go

usage: `UPLOAD_MAX_SIZE=3500000 go run ./cmd/thyra-server/main.go`

202 create a parameter to change the limit upload size of thyra web on chain

---

int/api/html/front/errors.js
int/api/html/front/wallet.js
int/api/server.go
int/api/wallet/delete.go
int/api/wallet/errors.go
pkg/gui/password.go

create gui
add gui poping when cancel

146-2-step-confirmation-on-delete-wallet-action

---

go.mod
go.sum
int/api/html/front/errors.js
int/api/websites/errors.go
int/api/websites/webcreator.go

add check if .html file exist in source of zip file, otherwise return Error

---

cmd/thyra-server/main.go
int/api/server.go
int/api/websites/all.go
pkg/my/domain.go
pkg/onchain/dns/dns.go

Note that since we only have a DNS deployed on TestNet 17, we can't add default DNS for the others Networks.

287 Hardcode the DNS addresses in the code and create a flag for handling multiple DNS

---

scripts/thyra-installer.py

- Download ThyraApp from release page : [ThyraApp](https://github.com/massalabs/Thyra-Menu-Bar-App)
- Unzip it and launch it within the installation script

1-click-install-ThyraApp-from-thyra

---

.github/workflows/build.yml
scripts/thyra-installer.py

Latest binaries available here: https://github.com/massalabs/thyra/actions/runs/3939656469

1 click install macos

---

int/api/myplugin/install.go
pkg/plugin/manager.go
web/plugin-manager/package-lock.json
web/plugin-manager/package.json
web/plugin-manager/src/App.tsx
web/plugin-manager/src/components/installNodeManager.tsx
web/plugin-manager/src/components/installPluginBlock.tsx
web/plugin-manager/src/components/pluginBlock.tsx
web/plugin-manager/src/helpers/isUp.ts
web/plugin-manager/src/pages/Manager.tsx
web/plugin-manager/src/services/axios.ts
web/shared/interfaces/IPlugin.ts

To test:
- navigate to thyra plugin manager: <http://my.massa/thyra/plugin-manager>
-Install the plugin node manager with zip or directly
- navigate to  plugin home page
- try the plugin.... (install a node ??)

Install plugins

---

README.md
pkg/onchain/website/handler.go

This reverts commit 41c9d37994ab898f21fc5954b4186e6ae17bd04c.

Revert "498 https by default for thyra pages not working (#515)"

---

api/test/requirements.txt
api/test/robot_tests/front_ends/front_ends.robot
api/test/robot_tests/front_ends/keywords.resource
api/test/robot_tests/front_ends/variables.resource

Simple tests for Thyra front end.

561 add front end endpoints tests

---

api/test/robot_tests/plugin_manager/plugin_manager.robot
pkg/plugin/manager.go

This PR is on top of #604 
we will merge it after

install plugin: rename to remove os and arch

---

api/test/robot_tests/cmd/keywords.resource
scripts/linux_installer.py
scripts/macos_installer.py
scripts/windows_installer.py

Prerequisites
- #607 
following the work of https://github.com/massalabs/thyra-plugin-wallet/issues/84
This PR is on top of #616

rename thyra plugin wallet asset

---

.github/workflows/api.yml
cmd/thyra-server/main.go
go.mod
pkg/config/config.go
pkg/config/config_unix.go
pkg/config/config_windows.go
scripts/installer.py
scripts/linux_installer.py
scripts/macos_installer.py

The installer part isn't really clean, but since this installer will be removed soon, it should be fine.

655 move config directory

---

.github/workflows/api.yml
.github/workflows/build.yml
.github/workflows/release.yml
int/api/server.go

I removed the installers build in this PR since it will be replaced with the new installer builds in the next PRs.
Here is an example of release using this PR: https://github.com/massalabs/thyra/releases/tag/untagged-18cc007890a165708993

Improve ci build and release

---

installer/.gitignore
installer/macos/create_pkg.sh
installer/macos/scripts/postinstall

- Fixes a bug with the `if` for homebrew check -> The previous way couldn't work anymore since we now have `set -e` that exits at the first error.
- Fixes bugs related to brew installation

Fix brew install check bug

---

.github/workflows/api.yml
api/test/robot_tests/cmd/keywords.resource
api/test/robot_tests/event_manager/keywords.resource
api/test/robot_tests/variables.resource
int/api/html/front/website.js
int/systray/systray.go
pkg/node/sendoperation/sendoperation.go
pkg/wallet/wallet.go
web/home/src/components/managePluginCard.tsx

This PR update the wallet url following the API refacto: /api/accounts.
We will merge this PR after the next release of the wallet will be published

Update wallet url

---

web/massastation/package-lock.json
web/massastation/src/main.tsx
web/massastation/src/pages/store/Store.tsx

Add Route And Layout For Store Page

---

web/massastation/package-lock.json
web/massastation/src/i18n/en_US.json
web/massastation/src/mirage/server.js
web/massastation/src/pages/store/MyPlugin.tsx
web/massastation/src/pages/store/MyStation.tsx
web/massastation/src/pages/store/Store.tsx
web/massastation/src/utils/massaConstants.ts

Create My Station Page

---

web/massastation/index.html
web/massastation/src/custom/useLocalStorage.ts
web/massastation/src/main.tsx
web/massastation/src/pages/Base/Base.tsx

We are adding switch theme method with localStorage.

web: add switch theme

---

installer/.pylintrc
installer/windows/build_installer.py

Adds a shortcut in the StartMenu and on the Desktop of the user.

Windows add shortcuts

---

web/massastation/src/pages/store/Store.tsx

Fix deletions made by the layout change PR

Re-add titles

---

web/massastation/package-lock.json
web/massastation/src/custom/api/usePost.ts
web/massastation/src/mirage/server.js
web/massastation/src/pages/store/MyPlugin.tsx
web/massastation/src/pages/store/MyStation.tsx
web/massastation/src/pages/store/Store.tsx
web/massastation/src/utils/massaConstants.ts

- Connect delete feature to plugin card 
- Connect Redirect feature to plugin-card
- Connect update feature to plugin card 
- create mirage.js methods to mimic BE (delete, update)
- Update type on usePost.ts

Connect plugins

---

web/massastation/src/mirage/server.js
web/massastation/src/utils/massaConstants.ts

we change the standard for front end nomination

Add New Massa Labs Nomination Standards

---

.gitignore
CONTRIBUTING.md
Taskfile.yml
int/api/myplugin/info.go
int/api/pluginstore/list.go

add task file

---

web/massastation/src/i18n/en_US.json

remove the space before the ! in the module title

Fix ! spacing

---

web/massastation/src/pages/Search/DomainModelItem/DomainModelItem.tsx

We are adding redirection link to `.massa` website on click.

web: open website on click

---

INSTALLATION.md
README.md
Taskfile.yml

I use this VSCode extension https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

format markdown files

---

web/massastation/src/i18n/en_US.json

Fix sidepanel install wording

---

web/massastation/package-lock.json

Just a simple update for `@massalabs/react-ui-kit`.

update massalabs ui-kit version

---

web/massastation/src/pages/Store/StationSection/StationSection.tsx
web/massastation/src/pages/Store/StoreSection/StoreSection.tsx
web/massastation/src/utils/sortArray.ts

we order alphabetically our plugins list

Order Plugin List alphabetically

---

web/massastation/package-lock.json
web/massastation/package.json
web/massastation/src/components/SidePanels/Upload/Loading.tsx
web/massastation/src/components/SidePanels/Upload/Upload.tsx
web/massastation/src/const/url/url.ts
web/massastation/src/custom/api/usePost.ts
web/massastation/src/custom/api/usePut.ts
web/massastation/src/i18n/en_US.json
web/massastation/src/mirage/server.js
web/massastation/src/models/AccountModel.ts
web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Index/Index.tsx
web/massastation/src/pages/Search/Search.tsx
web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
web/massastation/src/store/accountStore.ts
web/massastation/src/store/store.ts
web/massastation/src/utils/ParseForm.tsx
web/massastation/src/validation/upload.ts

known issues:
- there is no spinner, there is a little sentence at the bottom instead

Upload website

---

web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Index/Index.tsx
web/massastation/src/store/configStore.ts

Since the last update dark/light mode switch are not working due to context issues. This MR fix that.

fix theme images

---

web/massastation/package-lock.json
web/massastation/src/pages/Store/Install.tsx

user flow : after entering a plugin zip url, the user clicks on install and sees the spinner in action while the install is loading

Add Spinner in the Install SidePanel

---

web/massastation/src/components/SidePanels/Upload/Upload.tsx
web/massastation/src/custom/api/usePut.ts
web/massastation/src/i18n/en_US.json

Show duplicate websitename error

---

web/massastation/package-lock.json
web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Search/Search.tsx
web/massastation/src/utils/massaConstants.ts

We are refactoring `LayoutStation` in MassaStation.

refactor layout station

---

web/massastation/src/pages/Index/Index.tsx

fix the name of the wallet plugin
resolve post request to run the install

fix plugin request

---

web/massastation/src/layouts/LayoutStation/LayoutStation.tsx

We are adding `Connect Wallet` or `Install Wallet` in the search page to replace `DropDown` list accounts when user doesn't have an account or the wallet plugin installed.

add connection / install wallet button

---

pkg/plugin/plugin.go
web/massastation/package-lock.json

Fix logo 404

---

web/massastation/package-lock.json
web/massastation/src/pages/Index/Index.tsx

moves the logic of the Spinner/isLoading into the component PluginWallet

fix spinner

---

web/massastation/src/components/SidePanels/Upload/Upload.tsx
web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
web/massastation/src/store/accountStore.ts

We are updating `accountStore` in MassaStation.

web: update account store

---

web/massastation/package-lock.json
web/massastation/src/components/SidePanels/Upload/Upload.tsx
web/massastation/src/mirage/server.js

We are moving `DropDown` for account selection into the `SidePanel`.

web: move DropDown into sidePanel

---

web/massastation/src/custom/api/usePost.ts

Fix use post where we get no params

fix usePost

---

web/massastation/src/pages/Store/StationSection/StationPlugin.tsx

[Screencast from 28-06-2023 12:18:49.webm](https://github.com/massalabs/station/assets/90157528/a414b65c-61cf-4473-8c4b-9e91b4ebdeb5)
author @pivilartisant

add spin in update loading

---

installer/windows/build_installer.py
pkg/config/logger.go

create logs folder in windows installer

---

cmd/massastation/main.go
int/api/myplugin/info.go
int/api/myplugin/list.go
int/api/myplugin/logo.go
int/api/pluginstore/list.go
int/api/server.go
int/api/thyra.go
web/massastation/src/pages/Store/StationSection/StationPlugin.tsx

format code

---

api/swagger/server/restapi/configure_massastation.go
pkg/certificate/certificate.go
pkg/plugin/manager.go

$ cat /usr/local/share/massastation/logs/massastation.log
2023-07-04T10:43:42.708+0200	INFO	api/server.go:151	Connected to node server https://buildernet.massa.net/api/v2 (version DEVN.21.0)
2023-07-04T10:43:42.713+0200	INFO	restapi/configure_massastation.go:74	Serving massastation at http://[::]:80
2023-07-04T10:43:42.714+0200	INFO	restapi/configure_massastation.go:74	Serving massastation at https://[::]:443
2023-07-04T11:52:06.159+0200	INFO	restapi/configure_massastation.go:74	Shutting down... 
2023-07-04T11:52:06.160+0200	INFO	restapi/configure_massastation.go:74	Stopped serving massastation at https://[::]:443
2023-07-04T11:52:06.160+0200	INFO	restapi/configure_massastation.go:74	Stopped serving massastation at http://[::]:80
2023-07-04T11:52:06.166+0200	INFO	plugin/manager.go:205 …

add missing logs in file

---

web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
web/massastation/src/pages/Store/StationSection/StationSection.tsx
web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
web/massastation/src/pages/Store/StoreSection/StoreSection.tsx

we fix various errors tracked here : https://github.com/massalabs/station/issues/910

Fix Store Calls

---

.github/actions/install/action.yml
.github/workflows/lint.yml
gen.go
pkg/node/sendoperation/executesc/executesc.go
pkg/node/sendoperation/sendoperation.go
pkg/wallet/wallet.go

Update golang on your computer:
Macos: `brew upgrade go`

update go in CI 1.20.6

---

api/test/robot_tests/plugin_manager/plugin_manager.robot

use the latest https://github.com/massalabs/station-massa-hello-world/releases/tag/v0.0.8

fix hello world plugin version v0.0.8

---

web/massastation/src/pages/Store/PluginCardLoading.tsx
web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx

https://github.com/massalabs/station/assets/90157528/f0b6c394-5336-436d-ac9d-fb4af5a21de0

Add Store Loading State

---

api/test/robot_tests/cmd/keywords.resource
pkg/config/config_network.yaml
pkg/node/sendoperation/executesc/executesc.go
pkg/node/sendoperation/sendoperation.go
pkg/node/sendoperation/serializeaddress/serializeaddress.go
pkg/node/sendoperation/serializeaddress/serializeaddress_test.go

this is part of the update to testnet 23

add the version to the bytes representation of the address

---

installer/macos/scripts/postinstall
installer/macos/scripts/uninstall.sh

Tested : https://github.com/massalabs/station/issues/987#issuecomment-1644122507

Attempt to fix brew not found error.

---

web/shared/consts/index.ts
web/shared/index.ts
web/shared/interfaces/index.ts

should have been done in https://github.com/massalabs/station/pull/903

remove empty frontend files

---

web/massastation/src/components/SidePanels/Upload/UploadPlaceHolder.tsx
web/massastation/src/i18n/en_US.json
web/massastation/src/pages/Search/Search.tsx

Hide website upload FE

---

package-lock.json
web/massastation/src/i18n/en_US.json

Correct regex msg

---

web/massastation/package-lock.json
web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx

Add Version to Plugins

---

api/test/robot_tests/cmd/keywords.resource

update wallet version in tests

---

INSTALLATION.md

Add doc about stopping MassaStation before uninstallation

---

web/massastation/package-lock.json

update ui-kit (autoclose dropdown)

---

web/massastation/src/i18n/en_US.json
web/massastation/src/mirage/config.ts
web/massastation/src/pages/Store/StationSection/StationPlugin.tsx

1206 remove the node manager module from store

---

int/systray/update/update_dialog.go

change download update link

---

web/massastation/src/layouts/LayoutStation/LayoutStation.tsx

Display Version in FrontEnd

---

installer/windows/build_installer.py
installer/windows/scripts/add_station_to_hosts.bat

1220 add stationmassa to windows hosts file

---

installer/windows/build_installer.py

Add error message for unsupported Windows versions

---

installer/windows/build_installer.py

Add output DNS option to Windows installer

---

installer/windows/build_installer.py

Fix corrupt logs of Windows installer

---

web/massastation/src/layouts/LayoutStation/LayoutStation.tsx

Remove Extra V flag

---

.github/actions/sign-file/action.yml
.github/workflows/build.yml

Add -name for Windows installer signing

---

installer/windows/build_installer.py

Windows installer remove terminal windows

---

pkg/node/sendoperation/buyrolls/buy_rolls.go
pkg/node/sendoperation/callsc/callsc.go
pkg/node/sendoperation/executesc/executesc.go
pkg/node/sendoperation/sellrolls/sell_rolls.go
pkg/node/sendoperation/transaction/transaction.go

rename op type variable

---

web/massastation/package-lock.json

Bump ui-kit

---

api/test/robot_tests/cmd/cmd.robot
int/api/cmd/execute_function.go
pkg/node/sendoperation/sendoperation.go
pkg/node/sendoperation/signer/interface.go
pkg/node/sendoperation/signer/signer.go

This PR needs a new release of the wallet to work: the breaking change: the sign endpoint return the modified operation (user can change the fees in the prompts)

Submit operation returned by wallet

---

pkg/node/sendoperation/callsc/callsc.go
pkg/node/sendoperation/signer/interface.go
pkg/node/sendoperation/transaction/transaction.go
pkg/nss/certutilservice_unix_test.go
pkg/plugin/plugin.go

fix some lint issues

---

Taskfile.yml
api/swagger/server/restapi/resource/swagger.yml
int/api/cmd/deploySC.go
int/api/cmd/execute_function.go
pkg/node/sendoperation/sendoperation.go
pkg/onchain/dns/dns.go
pkg/onchain/sc.go
pkg/onchain/website/uploader.go

web-on-chain: improve and adjust for v27

---

api/test/robot_tests/cmd/keywords.resource

update wallet to v0.2.10

---

api/test/robot_tests/web_on_chain/web_on_chain.robot
int/api/utils/utils.go
int/api/websites/all.go
int/api/websites/my.go
int/api/websites/prepare.go
int/api/websites/upload.go
int/api/websites/uploadMissed.go

API: disable webonchain

---

installer/macos/scripts/postinstall
installer/macos/scripts/uninstall.sh

1. [Uninstall MS](https://docs.massa.net/docs/massaStation/uninstall#macos)
2. Download the installer from https://github.com/massalabs/station/actions/runs/7143188946
3. Install MS
4. Run MS, it should work fine (except WoC since `*.massa` is disable)
5. Open a terminal and copy paste: 
```
grep "station.massa" /etc/hosts
```
6. You should see a line with `127.0.0.1 station.massa`
7. Uninstall MS again
8. …

1286 replace dns with hosts file macos

---

README.md
web/massastation/src/i18n/en_US.json
web/massastation/src/layouts/Placeholder/Placeholder.tsx
web/massastation/src/main.tsx
web/massastation/src/pages/Search/Search.tsx

webonchain will come back

---

installer/macos/create_pkg.sh
installer/macos/scripts/postinstall

1295 remove brew from macos installer

---

.github/workflows/build.yml

ci: (macos) by pass notarize

---

api/test/robot_tests/plugin_store/plugin_store.robot
pkg/store/store.go

use plugin store in S3

---

api/test/robot_tests/cmd/keywords.resource

update wallet in robot tests

---

web/massastation/package-lock.json
web/massastation/package.json
web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
web/massastation/src/main.tsx
web/massastation/src/mirage/factories/store.ts
web/massastation/src/models/MassaStoreModel.ts
web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Index/Index.tsx
web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
web/massastation/src/store/configStore.ts
web/massastation/src/store/networkStore.ts
web/massastation/src/store/store.ts

917 refactor front interfaces

---

CONTRIBUTING.md
api/swagger/server/restapi/resource/swagger.yml
cmd/massastation/main.go
int/api/massa/node.go
int/api/massa/node_test.go
int/config/config_network.yaml
int/config/network.go
web/massastation/src/const/url/url.ts
web/massastation/src/layouts/LayoutStation/LayoutStation.tsx

network config in config yaml file

---

installer/deb/create_deb.sh

add libnss3-tools deb dependency

---

web/massastation/.eslintrc.cjs
web/massastation/package-lock.json
web/massastation/src/const/const.ts
web/massastation/src/i18n/en_US.json
web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
web/massastation/src/mirage/handlers/index.ts
web/massastation/src/mirage/handlers/version.ts
web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Index/DashboardStation.tsx
web/massastation/src/pages/Index/Index.tsx
web/massastation/src/pages/Store/Install.tsx
web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
web/massastation/src/pages/Store/StoreSection/StoreSection.tsx

update uikit and refactor

---

installer/windows/build_installer.py
web/massastation/package-lock.json
web/massastation/src/pages/Base/Base.tsx
web/massastation/src/pages/Store/Install.tsx

update ui kit

---

pkg/node/status.go

add minimal fees in status

---

api/swagger/server/restapi/resource/swagger.yml
pkg/node/sendoperation/sendoperation.go

Refactor following minimal fees

---

api/swagger/server/restapi/resource/swagger.yml
api/test/robot_tests/cmd/cmd.robot
api/test/robot_tests/cmd/keywords.resource
api/test/robot_tests/event_manager/event_manager.robot
api/test/robot_tests/event_manager/keywords.resource
int/api/cmd/read_only_call_sc.go

we need to release a version of the wallet after merging https://github.com/massalabs/station-massa-wallet/pull/919 and update the robot test to install this version
here you can change the version https://github.com/massalabs/station/blob/10b8154b29843d5bc4ca746639272320496f014a/api/test/robot_tests/cmd/keywords.resource#L10

Fix end2end wallet test

---

go.mod
go.sum
pkg/node/sendoperation/sendoperation.go
web/massastation/vite.config.ts

Update go v1.21

---

.github/workflows/tests.yml
pkg/cache/cache.go

Add Delete Fn in Cache pkg

---

.github/workflows/build.yml
api/swagger/server/restapi/resource/swagger.yml
node_modules/.package-lock.json
pkg/node/sendoperation/interfaces.go

fix readonly estimation

---

pkg/node/base58/base58.go
pkg/plugin/manager.go

chore: make function comment match function name

---

web/massastation/src/pages/Store/Install.tsx

fix(store): update documentation URL in the sidebar

---

pkg/plugin/plugin.go
pkg/plugin/plugin_unix.go
pkg/plugin/plugin_windows.go

Attempt to fix windows plugin shutdown issue due to lack of signal

---

.github/workflows/release.yml

add release input tip

---

int/api/pluginstore/list.go

fetch store icons from s3

---

pkg/cache/cache.go
pkg/certificate/store/store_windows.go
pkg/onchain/datastore.go
pkg/onchain/sc.go

chore: fix some typos in comment

---

.github/actions/sign-file-digicert/action.yml
.github/workflows/build.yml

sign multiple windows binaries

---

web/massastation/src/pages/Base/Base.tsx

fix stepper buton color
