.github/workflows/CD.yml
This workflow will allow us to create release easily and automatically add binaries to a release as release assets.
=> Add release handling using Github Actions

pkg/onchain/sc.go, pkg/onchain/website/uploader.go
Corrected by puting an offset for each async operations.
Before => We were sending N operations with the expiry = actualPeriod + 15
Now => We are sending N operations with the expiry = actualPeriod + (5 + 2*  index )
=> Store big website ( DUSA bug )

int/api/server.go
The application was not quit properly. This PR defers the call to the quit function to execute it in any case.
Before this PR, the bug was that the application was still running event after submitting the password.
=> improve quit gui

README.md
i faced some linter issues with some PRs, want to share how i resolved them.
=> golangci-lint how to

int/api/html/front/website.js
The chunk size was computed with b64 encoded data. Now it's computed with binary data to match our new model.
=> Read file as binary instead of b64 string

.github/actions/install/action.yml
The Windows build in the `build` workflow [uses `ubuntu-latest`](https://github.com/massalabs/thyra/blob/00a04424e6a693eb660d9478e310811b3b00f555/.github/workflows/build.yml#L38).
So we need to check if the `inputs.os` starts with `ubuntu-` instead of checking for a perfect match.
=> Fix Windows build on main.

.github/actions/install/action.yml, .github/workflows/lint.yml
To speedUp the CI, Only do the minimum for the linting process to run.
This save around 45 seconds !
=> remove full install from lint workflow

.github/workflows/build.yml
This PR focusses on fixing the lack of permissions installer binaries.
Please check that you can run the installer binary from [the latest build](https://github.com/massalabs/thyra/actions/runs/4386599576). (without having to `chmod +x` the binary)
=> 474-improve-thyra-installation-scripts

pkg/plugin/plugin.go
In some cases, like trying to execute the `start` command on a plugin that was already running, the function exited with an error and the lock was never released. 
This PR fixes this issue.
=> Fix an error due to a misplaced mutex unlock in Plugin Start function

.github/workflows/api.yml, api/test/robot_tests/plugin_store/plugin_store.robot
I added the variable for `node-server` just to make sure tests are working properly. As discussed with the team, I put back `node-server` to `TESTNET`. 
You can see [b58cad9](https://github.com/massalabs/thyra/pull/586/commits/b58cad95ef459855fddfd740bd764d4297e51702) which contains the tests running on `INNONET`.
=> Add Plugin Store tests

README.md
Fixed the redirection towards the installation guide from [Installation Guide](./INSTALL.md) to [Installation Guide](./INSTALLATION.md). Previously while trying to access the install guide it would return a 404 page not found.
=> Install Thyra Hyperlink 404 fix

.github/workflows/build.yml
During build in the CI, `$VERSION` was not properly set when building a non release build. 
Those changes ensure that `$VERSION` is either set to `{LAST_VERSION}-dev` for a non dev build, or to the given input version if it is a release build.
=> Fix missing $VERSION in installer scripts.

web/massastation/src/i18n/en_US.json
BEFORE 
"browse": "Browse the store below and manage plugin you've installed in this section"
AFTER
"browse": "Browse the store below and manage plugins you've installed in this section"
=> Fix plural

web/massastation/src/main.tsx
We fix the bug created by the base url variable that breaks mirage
=> fix mirage

web/massastation/src/pages/Store/StationSection/StationPlugin.tsx, web/massastation/src/pages/Store/StationSection/StationSection.tsx
we change the font size when there is no plugin  + an extra ";" that was lost in the html
=> Station Store/Station FE QA fix

web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
context : corrected invalid url in the post method : `url?param:value?` instead of `url?param:value`
( happened with the changes on the usePost method)
=> fix install plugin from store

web/massastation/src/pages/Index/Index.tsx
It's a temporary fix:
When the Index page is displayed, we display the Dashboard components with PluginWallet. The dashboard is a parent component of PluginWallet. So when there's a change to the "pluginWalletIsInstalled" variable, the Dashboard doesn't update. So the PluginWallet remains in an inactive state at all times.
with a Key we force the component to be updated.
=> fix dashboard

web/massastation/src/pages/Index/Index.tsx
this will fix:
> 
> When the wallet is installed, and I click on "Launch", I'm redirected to the wallet page. --> KO
> Expected: I want the wallet to be opened in another tab (it is another app so it must open in another tab, contrary to the search or store pages that are part of the same app ;) )
from https://github.com/massalabs/station/issues/822#issuecomment-1603116073
=> fix link Launch button

web/massastation/src/pages/Index/Index.tsx
goal: add spinner during installation of plugin.
Local installation is very quick. You can add this code for testing purposes:
```
setTimeout(() => {
console.log('timeout');
setIsLoading(false);
}, 10000);
```
=> add spinner in install plugin on homepage

cmd/massastation/main.go, int/api/myplugin/plugin.go, int/api/server.go, pkg/plugin/manager.go
- Refactor: move creation of plugin manager
- run all plugin after starting server (plugins register, they need the server to be started)
- stop all plugins on fyne app stop
=> stop all plugin on app quit

web/massastation/src/pages/Index/Index.tsx
This removes the double scroll present on mac os massaStation application
=> Remove Scroll Behavior From Home Page

installer/windows/build_installer.py, installer/windows/scripts/configure_acrylic.bat, installer/windows/scripts/configure_network_interfaces.bat, installer/windows/scripts/generate_certificate.bat, installer/windows/scripts/reset_network_interfaces.bat
Fixes some errors due to empty variables. This was due to how we handled logs in those scripts.
=> Fix installer logs errors

installer/windows/build_installer.py
This pull request fix a bug on windows, on any browser, navigating to http://flappy.massa/ failed because the websitesCache directory wasn't created and golang code can't do it because it's read only, so this fix creates this directory during installation.
This bug raise to other questions:
- GetConfigDir on windows returns C:\Program Files (x86)\MassaStation whereas it could return C:\Users\X\AppData\Local\MassaStation
- the error wasn't logged into the log file because it's a panic serving of goswagger.
=> create websites cache dir on install on windows

int/api/server.go
to test : remove the wifi & run massastation
```
2023-07-06T10:40:20.320+0200    ERROR   api/server.go:150       Could not get node version: calling get_status: rpc call get_status() on https://buildernet.massa.net/api/v2: Post "https://buildernet.massa.net/api/v2": sending http request '&{Method:POST URL:https://buildernet.massa.net/api/v2 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[application/json] Content-Type:[application/json]] Body:{Reader:0xc000620120} GetBody:0x6fd460 ContentLength:46 TransferEncoding:[] Close:false Host:buildernet.massa.net Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc0000420d0}': dial tcp: lookup buildernet.massa.net: no such host
2
```
=> remove fatal error if the store cannot be fetched

api/swagger/server/restapi/resource/swagger.yml, int/api/pluginstore/list.go, pkg/plugin/plugin_test.go, pkg/store/store.go
We're adding a field `isCompatible` that returns true if massa station's version is compatible with the plugin requirements
=> return plugin compability in the store

int/config/check.go
If an error occur during `checkCertificate`, then `checkNSS` will not be executed. This PR fix this.
=> don't return no blocking error immediatly

pkg/plugin/manager.go, pkg/plugin/manager_test.go, pkg/plugin/plugin.go, web/massastation/src/i18n/en_US.json
Part of https://github.com/massalabs/station-massa-wallet/issues/423
This PR allow plugin manager to install a plugin as a .app directory, for Mac OS application. This allow to have the proper logo in the dock on MacOS.
To test:
write this node js script into `store-mock-sever.js`
```
const http = require('http');
const fs = require('fs');
const path = require('path');
if (process.argv.length !== 3) {
console.error('Usage: node file-server.js <file-path>');
process.exit(1);
}
const filePath = process.argv[2];
const fileName = path.basename(filePath);
const server = http.createServer((req, res) => {
// Set the headers to specify the file download
res.setHeader('Content-disposition', `attachment; filename=${fileName}`);
res.setHeader('Content-type', 'application/octet-stream');
// Read the …
```
=> Install plugin macos app

pkg/plugin/manager.go, pkg/plugin/manager_test.go
Now that wallet account .yaml files are store on another location on the computer that the massa station directory, we can remove the code that kept the .yaml file while deleting the wallet plugin.
=> clean code uninstall plugin

web/massastation/package-lock.json, web/massastation/src/pages/Store/StationSection/StationPlugin.tsx, web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
This is a follow up PR of https://github.com/massalabs/ui-kit/pull/339. 
Now the "v" string is contained in ui-kit
=> Clean Plugin Version Display

pkg/node/events.go
Encountered this while working on https://github.com/massalabs/station-massa-wallet/pull/778
=> fix error formating with nil pointers

INSTALLATION.md
This is a common problem for Linux Massa Station users - https protocol is not available by default without adding CA to the browser.
=> Massa Station Linux HTTPS workaround

pkg/node/sendoperation/callsc/callsc.go, pkg/node/sendoperation/executesc/executesc.go, pkg/node/sendoperation/rolls.go, pkg/node/sendoperation/sendoperation.go, pkg/node/sendoperation/sendoperation_test.go, pkg/node/sendoperation/transaction/transaction.go
attempt to fix https://github.com/massalabs/station/issues/1131 by renaming the variables.
=> fix name operation type

INSTALLATION.md
=> rewrite Manually install the HTTPS certificate

api/test/robot_tests/cmd/cmd.robot, api/test/robot_tests/event_manager/keywords.resource, api/test/robot_tests/web_on_chain/web_on_chain.robot
=> robot test: use fee param of the endpoints

pkg/my/domain.go, pkg/onchain/dns/dns.go, pkg/onchain/website/uploader.go, pkg/wallet/wallet.go
=> rename struct Wallet into Account

installer/deb/scripts/postinst, installer/deb/scripts/postrm
1. [Uninstall MS](https://docs.massa.net/docs/massaStation/uninstall#linux)
2. Download the installer from https://github.com/massalabs/station/actions/runs/7180358277
3. Install MS
4. Run MS, it should work fine (except WoC since `*.massa` is disable)
5. Open a terminal and copy paste: 
```
grep "station.massa" /etc/hosts
```
6. You should see a line with `127.0.0.1 station.massa`
7. Uninstall MS again
8. …
=> 1286 replace dns with hosts file linux

pkg/nss/manager.go
=> nss functions: don't block on error

api/swagger/server/restapi/resource/swagger.yml, api/test/robot_tests/cmd/keywords.resource, api/test/robot_tests/keywords.resource, api/test/robot_tests/network/network.robot, api/test/robot_tests/web_on_chain/keywords.resource, int/api/pluginstore/list.go, int/config/config_network.yaml, web/massastation/src/i18n/i18n.ts, web/massastation/src/mirage/factories/network.ts
=> Mainnet config

api/swagger/server/restapi/resource/swagger.yml, int/api/pluginstore/list.go, web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
I want to install the wallet plugin but it not possible and there is a warning saying that it requires version 0.3.0 of massa station, I run version 0.6.1 of massa station.
This bug is introdoced in version 0.6.1, it was working well in 0.6.0. This PR introduce the bug: https://github.com/massalabs/station/pull/1316
The fix is to rename the variable isCompatible.
=> fix plugin is compatible

.github/workflows/build.yml, Taskfile.yml, tasks/Taskfile_darwin.yml, tasks/Taskfile_internal.yml, tasks/Taskfile_linux.yml, tasks/Taskfile_windows.yml
This PR improves the build system of MS to make it more reliable and build MS the same way between the CI and on our computers during development
=> Improve build system

.github/actions/install/action.yml, web/massastation/package-lock.json, web/massastation/src/assets/dashboard/MassaWallet.svg, web/massastation/src/assets/dashboard/index.ts, web/massastation/src/custom/hooks/useUpdatePlugin.ts, web/massastation/src/i18n/en_US.json, web/massastation/src/pages/Index/Dashboard/Bridge.tsx, web/massastation/src/pages/Index/Dashboard/Dusa.tsx, web/massastation/src/pages/Index/Dashboard/Foundation.tsx, web/massastation/src/pages/Index/Dashboard/MassaWallet.tsx, web/massastation/src/pages/Index/Dashboard/Purrfect.tsx, web/massastation/src/pages/Index/DashboardStation.tsx, web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
Changes: 
Plugin Wallet is now a component hosted in station repo (not ui-kit)
Update Plugin logic is contained in a custom hook and called in two places: dashboard and plugin store 
These changes enables the user to directly update MW plugin in the dashboard ui without having to navigate to the plugin store
=> Enable dashboard plugin update

api/swagger/server/restapi/resource/swagger.yml, int/api/cmd/execute_function.go
=> add description in the call sc

.github/workflows/api.yml, .github/workflows/build.yml, int/api/cmd/deploySC.go, pkg/node/sendoperation/readonlycall.go
=> fix deploysc coins field empty causing panic and fix gas estimation issue
